name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn

      - name: Prettier format
        run: yarn format

      - name: Eslint fix
        run: yarn lint

      - name: Run tests
        run: yarn test
